spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: 'org.hibernate.dialect.PostgreSQL81Dialect'